2018-07-13 10:24:24.289 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 10:24:24.341 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:24:24.345 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:24:24.348 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:24:24.352 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:24:24.354 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:24:24.355 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:24:24.355 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:24:24.361 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:24:24.361 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:24:24.362 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:26:46.854 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:26:46.922 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:26:46.926 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:26:46.928 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:26:46.933 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:26:46.934 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:26:46.936 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:26:46.936 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:26:46.942 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:26:46.942 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:26:46.943 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:34:39.750 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:34:39.828 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:34:39.832 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:34:39.834 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:34:39.839 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:34:39.840 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:34:39.841 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:34:39.842 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:34:39.849 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:34:39.849 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:34:39.849 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:35:16.702 [error] <0.224.0> gen_server <0.224.0> terminated with reason: socket_closed_unexpectedly
2018-07-13 10:35:16.702 [error] <0.224.0> CRASH REPORT Process <0.224.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
2018-07-13 10:35:16.702 [error] <0.222.0> Supervisor {<0.222.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.223.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.224.0> exit with reason socket_closed_unexpectedly in context child_terminated
2018-07-13 10:35:16.703 [error] <0.222.0> Supervisor {<0.222.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.223.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.224.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 10:35:24.549 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 10:35:24.610 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:35:24.614 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:35:24.616 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:35:24.621 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:35:24.622 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:35:24.623 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:35:24.623 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:35:24.630 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:35:24.630 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:35:24.631 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:52:57.160 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 10:52:57.221 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:52:57.226 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:52:57.228 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:52:57.232 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:52:57.233 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:52:57.235 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:52:57.235 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:52:57.241 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:52:57.241 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:52:57.242 [error] <0.225.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.ThrottleServ',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-07-13 10:52:57.242 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ThrottleServ',{'EXIT',{undef,[{'Elixir.ThrottleServ',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{'Elixir.Throttling.Application',start,[normal,[amqp]]}} in application_master:init/4 line 134
2018-07-13 10:53:48.902 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:53:48.964 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:53:48.968 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:53:48.970 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:53:48.975 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:53:48.976 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:53:48.978 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:53:48.978 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:53:48.983 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:53:48.983 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:53:48.985 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:58:23.552 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 10:58:23.592 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:58:23.597 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:58:23.599 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:58:23.603 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:58:23.605 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:58:23.606 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:58:23.606 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:58:23.612 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:58:23.612 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:58:23.612 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 10:58:23.722 [error] <0.226.0> gen_server 'Elixir.ThrottleServ' terminated with reason: {'module could not be loaded',[{'Elixir.Channel',open,[#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}],[]},{'Elixir.ThrottleServ',handle_info,2,[{file,"lib/throttling/throttle_serv.ex"},{line,32}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-07-13 10:58:23.722 [error] <0.226.0>@Elixir.Channel:open CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}) in gen_server:terminate/7 line 812
2018-07-13 10:58:23.723 [error] <0.225.0>@Elixir.Channel:open Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.226.0> exit with reason call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}) in context child_terminated
2018-07-13 10:58:23.724 [error] <0.245.0> gen_server 'Elixir.ThrottleServ' terminated with reason: {'module could not be loaded',[{'Elixir.Channel',open,[#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}],[]},{'Elixir.ThrottleServ',handle_info,2,[{file,"lib/throttling/throttle_serv.ex"},{line,32}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-07-13 10:58:23.724 [error] <0.245.0>@Elixir.Channel:open CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}) in gen_server:terminate/7 line 812
2018-07-13 10:58:23.724 [error] <0.225.0>@Elixir.Channel:open Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.245.0> exit with reason call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}) in context child_terminated
2018-07-13 10:58:24.189 [warning] <0.30.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 10:58:42.663 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:58:42.700 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 10:58:42.705 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 10:58:42.707 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 10:58:42.711 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 10:58:42.713 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 10:58:42.714 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 10:58:42.714 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 10:58:42.720 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 10:58:42.720 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 10:58:42.721 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:05:53.211 [error] <0.231.0> gen_server <0.231.0> terminated with reason: {socket_error,timeout}
2018-07-13 11:05:53.211 [error] <0.231.0> CRASH REPORT Process <0.231.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:terminate/7 line 812
2018-07-13 11:05:53.245 [error] <0.225.0> gen_server <0.225.0> terminated with reason: {socket_error,timeout}
2018-07-13 11:05:53.245 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:terminate/7 line 812
2018-07-13 11:05:53.245 [error] <0.224.0> Supervisor {<0.224.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5935>, <0.225.0>, <0.229.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.231.0> exit with reason {socket_error,timeout} in context child_terminated
2018-07-13 11:05:53.245 [error] <0.224.0> Supervisor {<0.224.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5935>, <0.225.0>, <0.229.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.231.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:05:53.246 [error] <0.223.0> Supervisor {<0.223.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.224.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.225.0> exit with reason {socket_error,timeout} in context child_terminated
2018-07-13 11:05:53.246 [error] <0.223.0> Supervisor {<0.223.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.224.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.225.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:08:43.527 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:08:43.604 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:08:43.608 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:08:43.610 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:08:43.615 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:08:43.616 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:08:43.617 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:08:43.617 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:08:43.624 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:08:43.624 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:08:43.638 [error] <0.220.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.638 [error] <0.220.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.221.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.221.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.221.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.222.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.222.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.222.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.223.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.223.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.223.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.223.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:08:43.675 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:09:53.859 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:09:53.889 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:09:53.894 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:09:53.896 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:09:53.900 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:09:53.902 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:09:53.903 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:09:53.903 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:09:53.910 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:09:53.910 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:09:53.911 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:09:54.002 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.002 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50118 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.002 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50118 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.002 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.008 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.008 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50119 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.008 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50119 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.008 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.016 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.016 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50120 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.016 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50120 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.016 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.024 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.025 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50121 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.025 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50121 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.025 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.025 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.076 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:10:32.482 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:10:32.520 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:10:32.524 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:10:32.526 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:10:32.530 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:10:32.532 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:10:32.533 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:10:32.533 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:10:32.540 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:10:32.540 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:10:32.543 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:10:32.654 [error] <0.230.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.230.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:32.654 [error] <0.227.0> Supervisor {<0.227.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5603>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.229.0>, {<<"client 127.0.0.1:50134 -> 127.0.0.1:5672">>,1}) at <0.230.0> exit with reason badarg in context child_terminated
2018-07-13 11:10:32.654 [error] <0.227.0> Supervisor {<0.227.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5603>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.229.0>, {<<"client 127.0.0.1:50134 -> 127.0.0.1:5672">>,1}) at <0.230.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:10:32.654 [error] <0.208.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason {shutdown,{gen_server,call,[<0.229.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.209.0>},60000]}} in context child_terminated
2018-07-13 11:10:32.660 [error] <0.247.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.247.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:33.190 [warning] <0.30.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:10:47.192 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:10:47.251 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:10:47.255 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:10:47.258 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:10:47.266 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:10:47.269 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:10:47.272 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:10:47.273 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:10:47.283 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:10:47.284 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:10:47.285 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:10:47.420 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:47.420 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50138 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:10:47.420 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50138 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:10:47.421 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:10:47.430 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:48.260 [warning] <0.30.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:11:27.850 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:11:27.881 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:11:27.886 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:11:27.889 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:11:27.893 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:11:27.894 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:11:27.896 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:11:27.896 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:11:27.901 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:11:27.901 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:11:27.903 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:11:28.033 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.033 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50150 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.033 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50150 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.034 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.049 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.050 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50151 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.050 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50151 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.051 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.062 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.063 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50152 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.063 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50152 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.063 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.071 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.071 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50153 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.072 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50153 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.072 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.072 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.110 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:12:02.412 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:12:02.448 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:12:02.456 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:12:02.459 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:12:02.468 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:12:02.471 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:12:02.473 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:12:02.474 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:12:02.482 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:12:02.482 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:12:02.483 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:12:02.622 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:12:02.622 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50157 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:12:02.623 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50157 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:12:02.623 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:12:02.632 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:12:03.241 [warning] <0.30.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:12:25.176 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:12:25.225 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:12:25.230 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:12:25.232 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:12:25.236 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:12:25.237 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:12:25.239 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:12:25.239 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:12:25.246 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:12:25.246 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:12:25.247 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:13:09.596 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:13:09.646 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:13:09.652 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:13:09.666 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:13:09.676 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:13:09.679 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:13:09.682 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:13:09.682 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:13:09.692 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:13:09.693 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:13:09.693 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:13:09.809 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:13:09.810 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50175 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:13:09.810 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50175 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:13:09.810 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:13:09.819 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:13:10.240 [warning] <0.30.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:15:43.644 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:15:43.708 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:15:43.715 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:15:43.719 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:15:43.729 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:15:43.732 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:15:43.735 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:15:43.735 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:15:43.751 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:15:43.751 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:15:43.754 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:15:43.892 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:15:43.892 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50207 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:15:43.892 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50207 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:15:43.893 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:15:43.903 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:15:44.279 [warning] <0.30.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:16:56.308 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:16:56.349 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:16:56.353 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:16:56.357 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:16:56.366 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:16:56.369 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:16:56.372 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:16:56.373 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:16:56.386 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:16:56.386 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:16:56.388 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:16:56.541 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:16:56.541 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50238 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:16:56.541 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50238 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:16:56.541 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:16:56.551 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:16:57.259 [warning] <0.30.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:17:04.805 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:04.854 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:17:04.858 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:17:04.860 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:17:04.864 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:17:04.866 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:17:04.867 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:17:04.867 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:17:04.873 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:17:04.874 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:17:04.875 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:17:05.034 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.034 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50242 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.035 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50242 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.035 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.047 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.047 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50243 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.047 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50243 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.048 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.056 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.056 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50244 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.057 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50244 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.057 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.066 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.066 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50245 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.066 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50245 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.066 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.277.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.067 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.099 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:17:15.991 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:16.056 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:17:16.060 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:17:16.062 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:17:16.067 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:17:16.068 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:17:16.069 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:17:16.069 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:17:16.077 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:17:16.077 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:17:16.078 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:17:16.201 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.202 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50246 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.202 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50246 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.203 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.222 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.223 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50247 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.223 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50247 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.223 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.233 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.233 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50248 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.234 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50248 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.234 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.243 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.243 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50249 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.243 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50249 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.244 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.244 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.266 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:17:24.778 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:24.813 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:17:24.818 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:17:24.820 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:17:24.826 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:17:24.828 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:17:24.830 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:17:24.830 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:17:24.841 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:17:24.841 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:17:24.843 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:17:24.968 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:24.968 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:24.978 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:24.978 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:25.000 [warning] <0.30.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:17:25.000 [error] <0.276.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:25.000 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:25.000 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:25.040 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 11:17:41.577 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:41.626 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:17:41.630 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:17:41.632 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:17:41.637 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:17:41.638 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:17:41.639 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:17:41.639 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:17:41.646 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:17:41.646 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:17:41.648 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:17:41.819 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:41.820 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:41.830 [error] <0.243.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:41.830 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:42.280 [warning] <0.30.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:18:47.605 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:18:47.648 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:18:47.652 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:18:47.655 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:18:47.662 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:18:47.666 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:18:47.670 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:18:47.671 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:18:47.685 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:18:47.685 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:18:47.687 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:18:47.899 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:18:47.899 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:18:47.908 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:18:47.908 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:18:48.319 [warning] <0.30.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:19:10.887 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:10.931 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:19:10.936 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:19:10.938 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:19:10.943 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:19:10.944 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:19:10.946 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:19:10.946 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:19:10.954 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:19:10.954 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:19:10.956 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:19:39.465 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:39.507 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:19:39.511 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:19:39.513 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:19:39.517 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:19:39.519 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:19:39.520 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:19:39.520 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:19:39.529 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:19:39.530 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:19:39.532 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:19:39.687 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:39.688 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:39.698 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:39.698 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:40.246 [warning] <0.30.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:19:57.422 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:57.468 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:19:57.472 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:19:57.474 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:19:57.478 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:19:57.480 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:19:57.481 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:19:57.481 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:19:57.487 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:19:57.487 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:19:57.489 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:19:57.643 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:57.643 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:57.649 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:57.649 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:58.245 [warning] <0.30.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:20:22.141 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:20:22.168 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:20:22.172 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:20:22.174 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:20:22.180 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:20:22.182 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:20:22.184 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:20:22.184 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:20:22.195 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:20:22.195 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:20:22.197 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:20:50.233 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:20:50.290 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:20:50.294 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:20:50.296 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:20:50.300 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:20:50.302 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:20:50.303 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:20:50.303 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:20:50.310 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:20:50.310 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:20:50.312 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:20:50.425 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:20:50.426 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50299 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:20:50.426 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50299 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:20:50.426 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:20:50.434 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:20:51.223 [warning] <0.30.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:22:30.521 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:22:30.583 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:22:30.590 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:22:30.594 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:22:30.601 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:22:30.602 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:22:30.603 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:22:30.603 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:22:30.612 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:22:30.612 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:22:30.613 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:22:49.137 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:22:49.188 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:22:49.192 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:22:49.194 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:22:49.200 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:22:49.202 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:22:49.206 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:22:49.207 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:22:49.220 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:22:49.220 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:22:49.221 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:23:02.715 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:23:02.745 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:23:02.751 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:23:02.754 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:23:02.762 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:23:02.764 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:23:02.767 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:23:02.767 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:23:02.780 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:23:02.780 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:23:02.782 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:39:38.403 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:39:38.444 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:39:38.451 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:39:38.454 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:39:38.464 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:39:38.469 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:39:38.472 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:39:38.472 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:39:38.484 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:39:38.484 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:39:38.486 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:41:03.000 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:41:03.043 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:41:03.047 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:41:03.049 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:41:03.057 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:41:03.058 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:41:03.061 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:41:03.061 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:41:03.073 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:41:03.073 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:41:03.074 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:41:05.260 [error] <0.220.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:05.260 [error] <0.220.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:05.260 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:07.240 [error] <0.243.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:07.240 [error] <0.243.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:07.241 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:09.250 [error] <0.260.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:09.250 [error] <0.260.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:09.250 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:11.265 [error] <0.277.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:11.265 [error] <0.277.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:11.266 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:29.549 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:42:29.604 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:42:29.608 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:42:29.610 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:42:29.616 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:42:29.618 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:42:29.620 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:42:29.620 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:42:29.633 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:42:29.633 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:42:29.635 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:42:31.856 [error] <0.220.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:31.856 [error] <0.220.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:31.856 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:44.424 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:42:44.489 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:42:44.497 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:42:44.501 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:42:44.508 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:42:44.510 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:42:44.512 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:42:44.512 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:42:44.522 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:42:44.522 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:42:44.525 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:42:46.727 [error] <0.209.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:46.727 [error] <0.209.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:46.727 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:48.726 [error] <0.232.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:48.727 [error] <0.232.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:48.727 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.232.0> exit with reason no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:05.784 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:43:05.832 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:43:05.836 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:43:05.838 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:43:05.846 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:43:05.847 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:43:05.849 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:43:05.850 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:43:05.865 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:43:05.865 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:43:05.869 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:43:08.120 [error] <0.209.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:08.120 [error] <0.209.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:08.120 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:10.120 [error] <0.232.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:10.120 [error] <0.232.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:10.120 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.232.0> exit with reason no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:12.129 [error] <0.249.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:12.129 [error] <0.249.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:12.129 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.249.0> exit with reason no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:14.138 [error] <0.266.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:14.138 [error] <0.266.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:14.139 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.266.0> exit with reason no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:16.147 [error] <0.283.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:16.147 [error] <0.283.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:16.148 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.283.0> exit with reason no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:18.155 [error] <0.300.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:18.155 [error] <0.300.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:18.155 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.300.0> exit with reason no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:53.232 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:43:53.305 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:43:53.315 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:43:53.320 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:43:53.330 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:43:53.332 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:43:53.334 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:43:53.335 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:43:53.344 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:43:53.344 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:43:53.345 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:43:53.528 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:43:53.528 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6022>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50598 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:43:53.529 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6022>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50598 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:43:53.529 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:43:53.545 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:43:54.334 [warning] <0.30.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 11:45:34.555 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:45:34.604 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:45:34.609 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:45:34.611 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:45:34.615 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:45:34.617 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:45:34.618 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:45:34.618 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:45:34.624 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:45:34.624 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:45:34.625 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:49:01.627 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 11:49:01.689 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:49:01.694 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:49:01.696 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:49:01.701 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:49:01.702 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:49:01.703 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:49:01.703 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:49:01.710 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:49:01.710 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:49:01.710 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:49:44.306 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:49:44.384 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:49:44.398 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:49:44.400 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:49:44.405 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:49:44.406 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:49:44.408 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:49:44.408 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:49:44.414 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:49:44.414 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:49:44.415 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:53:07.253 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:53:07.295 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:53:07.299 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:53:07.301 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:53:07.306 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:53:07.307 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:53:07.308 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:53:07.308 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:53:07.315 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:53:07.315 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:53:07.316 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:54:03.286 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:54:03.324 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:54:03.329 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:54:03.331 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:54:03.335 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:54:03.337 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:54:03.338 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:54:03.338 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:54:03.345 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:54:03.345 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:54:03.347 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 11:58:12.345 [error] <0.169.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.174.0> exit with reason normal in context child_terminated
2018-07-13 11:58:12.392 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 11:58:12.397 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 11:58:12.399 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 11:58:12.403 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 11:58:12.404 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 11:58:12.406 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 11:58:12.406 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 11:58:12.413 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 11:58:12.413 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 11:58:12.415 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:02:00.282 [error] <0.174.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.179.0> exit with reason normal in context child_terminated
2018-07-13 12:02:00.358 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:02:00.362 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:02:00.364 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:02:00.368 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:02:00.370 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:02:00.371 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:02:00.371 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:02:00.377 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:02:00.377 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:02:00.377 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:04:03.967 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:04:04.024 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:04:04.028 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:04:04.030 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:04:04.035 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:04:04.036 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:04:04.038 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:04:04.038 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:04:04.045 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:04:04.045 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:04:04.046 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:14:51.311 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:14:51.357 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:14:51.361 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:14:51.364 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:14:51.368 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:14:51.369 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:14:51.371 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:14:51.371 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:14:51.378 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:14:51.378 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:14:51.379 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:15:42.025 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:15:42.067 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:15:42.071 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:15:42.073 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:15:42.077 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:15:42.078 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:15:42.080 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:15:42.080 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:15:42.087 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:15:42.087 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:15:42.088 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:16:00.242 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 12:16:00.299 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:16:00.303 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:16:00.305 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:16:00.310 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:16:00.312 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:16:00.313 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:16:00.313 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:16:00.320 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:16:00.320 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:16:00.323 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:17:07.755 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:17:07.792 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:17:07.796 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:17:07.799 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:17:07.803 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:17:07.804 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:17:07.806 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:17:07.806 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:17:07.813 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:17:07.813 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:17:07.814 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:19:43.774 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.176.0> exit with reason normal in context child_terminated
2018-07-13 12:19:43.841 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:19:43.845 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:19:43.847 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:19:43.851 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:19:43.853 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:19:43.854 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:19:43.854 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:19:43.860 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:19:43.860 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:19:43.861 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:19:43.967 [error] <0.227.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:43.967 [error] <0.227.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:43.967 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.227.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:43.968 [error] <0.246.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:43.969 [error] <0.246.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:43.969 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.246.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:44.208 [warning] <0.30.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 12:19:53.699 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 12:19:53.736 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:19:53.740 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:19:53.742 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:19:53.747 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:19:53.748 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:19:53.749 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:19:53.749 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:19:53.755 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:19:53.755 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:19:53.758 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:19:53.862 [error] <0.209.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:53.862 [error] <0.209.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:53.862 [error] <0.208.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:53.863 [error] <0.228.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:53.863 [error] <0.228.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:53.863 [error] <0.208.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.228.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:54.177 [warning] <0.30.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 12:20:50.542 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:20:50.595 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:20:50.599 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:20:50.601 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:20:50.606 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:20:50.607 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:20:50.608 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:20:50.608 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:20:50.615 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:20:50.615 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:20:50.617 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:21:03.466 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:21:03.495 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:21:03.499 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:21:03.501 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:21:03.506 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:21:03.507 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:21:03.509 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:21:03.509 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:21:03.514 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:21:03.514 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:21:03.516 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:21:29.089 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:21:29.089 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:21:29.089 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:21:29.188 [error] <0.250.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.188 [error] <0.250.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.189 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.250.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.300 [error] <0.264.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.300 [error] <0.264.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.300 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.264.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.411 [error] <0.278.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.411 [error] <0.278.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.412 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.278.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.412 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.278.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:21:29.412 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 12:24:49.857 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 12:24:49.901 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:24:49.904 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:24:49.907 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:24:49.911 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:24:49.912 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:24:49.913 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:24:49.914 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:24:49.919 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:24:49.919 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:24:49.919 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:24:50.152 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:24:50.152 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:24:50.152 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.226.0> exit with reason bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:24:50.255 [error] <0.249.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.255 [error] <0.249.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.255 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.249.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.366 [error] <0.263.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.367 [error] <0.263.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.367 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.263.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.478 [error] <0.277.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.478 [error] <0.277.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.479 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.479 [error] <0.225.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:24:50.479 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 12:25:17.576 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:25:17.617 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:25:17.621 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:25:17.623 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:25:17.628 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:25:17.629 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:25:17.630 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:25:17.631 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:25:17.637 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:25:17.637 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:25:17.638 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:25:17.865 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:25:17.865 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:25:17.866 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:25:17.967 [error] <0.242.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:17.967 [error] <0.242.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [warning] <0.30.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2018-07-13 12:25:18.080 [error] <0.257.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [error] <0.257.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.257.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:25:18.191 [error] <0.271.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.191 [error] <0.271.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.191 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.271.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:25:18.192 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.271.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:25:18.192 [info] <0.31.0> Application throttling exited with reason: shutdown
2018-07-13 12:25:58.437 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:25:58.490 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:25:58.494 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:25:58.496 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:25:58.502 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:25:58.503 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:25:58.504 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:25:58.504 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:25:58.512 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:25:58.512 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:25:58.513 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:26:57.822 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:26:57.869 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:26:57.874 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:26:57.876 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:26:57.881 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:26:57.882 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:26:57.883 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:26:57.884 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:26:57.891 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:26:57.891 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:26:57.892 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:28:37.976 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:28:38.013 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:28:38.017 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:28:38.020 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:28:38.030 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:28:38.032 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:28:38.033 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:28:38.033 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:28:38.039 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:28:38.040 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:28:38.040 [info] <0.31.0> Application throttling started on node nonode@nohost
2018-07-13 12:29:20.454 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:29:20.525 [info] <0.31.0> Application lager started on node nonode@nohost
2018-07-13 12:29:20.529 [info] <0.31.0> Application xmerl started on node nonode@nohost
2018-07-13 12:29:20.531 [info] <0.31.0> Application jsx started on node nonode@nohost
2018-07-13 12:29:20.536 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-07-13 12:29:20.537 [info] <0.31.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-07-13 12:29:20.538 [info] <0.31.0> Application recon started on node nonode@nohost
2018-07-13 12:29:20.538 [info] <0.31.0> Application rabbit_common started on node nonode@nohost
2018-07-13 12:29:20.545 [info] <0.31.0> Application amqp_client started on node nonode@nohost
2018-07-13 12:29:20.545 [info] <0.31.0> Application amqp started on node nonode@nohost
2018-07-13 12:29:20.546 [info] <0.31.0> Application throttling started on node nonode@nohost
